<?php

namespace Mintreu\LaravelLayout\View\Themes;

use Mintreu\LaravelLayout\LaravelLayout;

class TallTheme extends LaravelLayout
{
    protected ?string $view = 'layout::layouts.themes.tall';


    protected function preConstruct()
    {
        $this->support['alpine'] = true;

        parent::preConstruct(); // TODO: Change the autogenerated stub
    }


}
