<?php

namespace Mintreu\LaravelLayout;

use Illuminate\Support\Facades\Blade;
use Illuminate\View\Compilers\ComponentTagCompiler;
use Mintreu\LaravelLayout\View\AppLayout;
use Mintreu\LaravelLayout\View\Theme;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Mintreu\LaravelLayout\Commands\LaravelLayoutCommand;

class LaravelLayoutServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('laravel-layout')
//            ->hasConfigFile()
            ->hasViews()
//            ->hasMigration('create_laravel-layout_table')
            ->hasCommand(LaravelLayoutCommand::class);
    }


    public function registeringPackage()
    {

        parent::registeringPackage(); // TODO: Change the autogenerated stub
    }


    public function bootingPackage()
    {
        Blade::component('layout::layout', AppLayout::class);
        Blade::component('layout::theme', Theme::class);
        parent::bootingPackage(); // TODO: Change the autogenerated stub
    }


}
