<?php

namespace Mintreu\LaravelLayout;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Str;
use Illuminate\View\Compilers\ComponentTagCompiler;
use Mintreu\LaravelLayout\Commands\Traits\hasFilesManipulator;
use Mintreu\LaravelLayout\Directives\BladeDirective;
use Mintreu\LaravelLayout\View\Layout;
use Mintreu\LaravelLayout\View\Theme;
use Mintreu\LaravelLayout\View\Themes\BootstrapTheme;
use Mintreu\LaravelLayout\View\Themes\TallTheme;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Mintreu\LaravelLayout\Commands\LaravelLayoutCommand;

class LaravelLayoutServiceProvider extends PackageServiceProvider
{


    public function configurePackage(Package $package): void
    {
        $package
            ->name('laravel-layout')
           ->hasConfigFile('layout')
            ->hasViews()
            ->hasCommand(LaravelLayoutCommand::class);
    }



    /**
     * @return void
     */
    public function bootingPackage()
    {
        $directives = new BladeDirective();
        $directives->loadLayoutDirectives();
        Blade::component('layout::layout', Layout::class);
        Blade::component('layout::blade', Theme::class);
        Blade::component('layout::tall', TallTheme::class);
        Blade::component('layout::bootstrap', BootstrapTheme::class);
        parent::bootingPackage(); // TODO: Change the autogenerated stub
    }


}
